server:
  port: 9981
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id : shop-backend
          uri : lb://SHOP-BACKEND
          predicates:
            - Path=/shop-backend/**
        - id : authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/authentication-service/**
        - id : other-service
          uri: lb://OTHER-SERVICE
          predicates:
            - Path=/other-service/**
  rabbitmq:
    host: localhost
    port: 5672
    username: micro-service-dev
    password: 2a55f70a841f18b97c3a7db939b7adc9e34a0f1b
    virtual-host: micro-service-dev

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

api :
  core:
    url: http://localhost:9090
    header: abnckasasas