
server:
  port: 9981

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id : shop-backend
          uri : lb://SHOP-BACKEND
          predicates:
            - Path=/shop-backend/**
        - id : authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/authentication-service/**
        - id : other-service
          uri: lb://OTHER-SERVICE
          predicates:
            - Path=/other-service/**
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

