server:
  port: 9981
spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id : account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/private/account-service/**
          filters:
            - JwtAuthenticationFilter
        - id : other-service
          uri: lb://OTHER-SERVICE
          predicates:
            - Path=/public/other-service/**
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/private/authentication-service/**
  rabbitmq:
    host: localhost
    port: 5672
    username: micro-service-dev
    password: 2a55f70a841f18b97c3a7db939b7adc9e34a0f1b
    virtual-host: micro-service-dev

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true


